site_name: The Cookbook
site_description: Website with receipes that I have cooked in the past.
site_url: https://almostengr.github.io/cookbook
copyright: Copyright 2020

# repository information
repo_url: https://github.com/almostengr/cookbook
repo_name: Github
remote_name: origin
remote_branch: gh-pages

# Development server details
# dev_addr: 192.168.57.117:8000
  
# extra_css: [css/extra.css]

# Appearance
theme:
  name: readthedocs
  # custom_dir: 'readthedocs'
  highlightjs: false
  language: en
  static_templates:
    - 404.html
  include_search_page: true
  search_index_only: false
  highlightjs: false
  hljs_languages: []
  include_homepage_in_sidebar: false
  prev_next_buttons_location: bottom
  navigation_depth: 4
  titles_only: true
  sticky_navigation: true
  collapse_navigation: true

use_directory_urls: true
strict: false

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true

extra:
  generator: false